[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_BASE_URL = "https://arslandede.org.tr"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
